export const GatewayErrorCode = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  ROUTER_ERROR: 'ROUTER_ERROR',
  STORAGE_ERROR: 'STORAGE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
} as const;

export const ProviderErrorCode = {
  NOT_IMPLEMENTED: 'PROVIDER_NOT_IMPLEMENTED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  LOGIN_REQUIRED: 'LOGIN_REQUIRED',
  UI_CHANGED: 'UI_CHANGED',
  CAPTURE_FAILED: 'CAPTURE_FAILED',
  TIMEOUT: 'TIMEOUT',
} as const;
