export { createError, type ErrorCode, ErrorCodes } from '@tessera-gateway/core/errors';
export type {
  CloseProviderResult,
  FocusProviderResult,
  LayoutMode,
  LayoutResult,
  LoadState,
  NormalizedResponse,
  OpenProviderResult,
  ParallelResult,
  PromptRequest,
  ProviderAuthMethod,
  ProviderBrowserState,
  ProviderCapabilities,
  ProviderError,
  ProviderInfo,
  ProviderInfoStatus,
  ProviderSummary,
  ResetSessionResult,
  RuntimeState,
  ToolResult,
} from '@tessera-gateway/core/providers/types';
